/**
 * Bundle dist/ into one browser-global file for the docs demo.
 *
 * Kintsugi has no runtime dependencies and its modules only import from each
 * other, so concatenating them in dependency order and stripping the module
 * syntax is enough — no bundler needed. Run after `npm run build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Dependency order: a module may only reference ones above it.
const MODULES = [
  'types',
  'preprocess',
  'scanners',
  'context',
  'inline-tokens',
  'inline-recovery',
  'table-shape',
  'inline-parser',
  'list-parser',
  'table-parser',
  'block-parser',
  'renderer',
  'index',
];

let out = `// Kintsugi — generated by scripts/build-docs.mjs. Do not edit.\n`;

for (const name of MODULES) {
  let src = readFileSync(join(root, 'dist', `${name}.js`), 'utf8');
  src = src
    .replace(/^\s*import[^;]*?;\s*$/gm, '')
    .replace(/^\s*export \{[^}]*\}[^;]*;\s*$/gm, '')
    .replace(/^\s*export \* from[^;]*;\s*$/gm, '')
    .replace(/\bexport (const|function|class|let|var) /g, '$1 ')
    .replace(/^\s*export default /gm, '')
    .replace(/^\/\/# sourceMappingURL=.*$/gm, '');
  out += `\n// ===== ${name} =====\n${src}`;
}

out += `\nwindow.Kintsugi = { parse, render, renderHtml };\n`;

const target = join(root, 'docs', 'kintsugi.bundle.js');
writeFileSync(target, out);

// Concatenating modules cannot represent an `import { x as y }` alias, and a
// missing binding only shows up at runtime — inside the parser's own
// never-throw handler, which turns it into a plausible-looking diagnostic.
// So exercise several documents and reject any internal error.
const sandbox = {};
new Function('window', out)(sandbox);

const PROBES = [
  ['broken table', '| a | b |\n| 1 | 2 |', 1],
  ['clean document', '# T\n\nText.\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n\n- one\n- two\n\n```js\nconst x = 1;\n```\n', 0],
  ['lists and fences', '1. Build:\n```sh\nmake\n```\n2. Ship\n', null],
  ['math and footnotes', 'See \\(x\\) and $y$[^1].\n\n[^1]: note\n', null],
];

for (const [name, src, expectedRepairs] of PROBES) {
  const r = sandbox.Kintsugi.render(src);
  const internal = r.diagnostics.filter((d) => /Internal parser error/.test(d.message));
  if (internal.length > 0) {
    throw new Error(`bundle smoke test "${name}" hit an internal error: ${internal[0].message}`);
  }
  if (expectedRepairs !== null) {
    const repairs = r.diagnostics.filter((d) => d.severity === 'repair').length;
    if (repairs !== expectedRepairs) {
      throw new Error(`bundle smoke test "${name}": expected ${expectedRepairs} repairs, got ${repairs}`);
    }
  }
}

console.log(`wrote docs/kintsugi.bundle.js (${(out.length / 1024).toFixed(0)} KB)`);
