/**
 * Bundle dist/ into one browser-global file for the docs demo.
 *
 * Kintsugi has no runtime dependencies and its modules only import from each
 * other, so concatenating them in dependency order and stripping the module
 * syntax is enough — no bundler needed. Run after `npm run build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Dependency order: a module may only reference ones above it.
const MODULES = [
  'types',
  'preprocess',
  'scanners',
  'context',
  'inline-tokens',
  'inline-recovery',
  'table-shape',
  'inline-parser',
  'list-parser',
  'table-parser',
  'block-parser',
  'renderer',
  'index',
];

let out = `// Kintsugi — generated by scripts/build-docs.mjs. Do not edit.\n`;

for (const name of MODULES) {
  let src = readFileSync(join(root, 'dist', `${name}.js`), 'utf8');
  src = src
    .replace(/^\s*import[^;]*?;\s*$/gm, '')
    .replace(/^\s*export \{[^}]*\}[^;]*;\s*$/gm, '')
    .replace(/^\s*export \* from[^;]*;\s*$/gm, '')
    .replace(/\bexport (const|function|class|let|var) /g, '$1 ')
    .replace(/^\s*export default /gm, '')
    .replace(/^\/\/# sourceMappingURL=.*$/gm, '');
  out += `\n// ===== ${name} =====\n${src}`;
}

out += `\nwindow.Kintsugi = { parse, render, renderHtml };\n`;

const target = join(root, 'docs', 'kintsugi.bundle.js');
writeFileSync(target, out);

// Fail loudly rather than shipping a bundle that does not evaluate.
const sandbox = {};
new Function('window', out)(sandbox);
const probe = sandbox.Kintsugi.render('| a | b |\n| 1 | 2 |');
if (!probe.html.includes('<table>') || probe.diagnostics.length === 0) {
  throw new Error('bundle smoke test failed');
}

console.log(`wrote docs/kintsugi.bundle.js (${(out.length / 1024).toFixed(0)} KB)`);
