/**
 * Pinned weights for the bold-line-as-heading classifier.
 *
 * Generated by scripts/train.mjs — do not hand-edit. Kept as a TypeScript
 * module rather than a JSON import so the package loads on every Node version
 * it claims to support and through every bundler: `import ... with { type:
 * 'json' }` is Node 22+, and this package supports Node 18.
 *
 * The feature order here must match FEATURE_NAMES in features.ts; classifier.ts
 * checks that at load time and disables the model rather than scoring against a
 * mismatched vector.
 */
export interface ModelFile {
  model: string;
  kind: string;
  trainedOn: number;
  featureNames: string[];
  weights: number[];
  threshold: number;
}

export const MODEL_WEIGHTS: ModelFile = {
  "model": "bold-line-heading",
  "kind": "logistic-regression",
  "trainedOn": 139788,
  "featureNames": [
    "bias",
    "ends_terminal_punct",
    "ends_colon",
    "has_clause_punct",
    "leading_enumeration",
    "words_norm",
    "chars_norm",
    "is_very_short",
    "digit_ratio",
    "uppercase_ratio",
    "is_all_caps",
    "is_cased_script",
    "title_case_score",
    "cjk_ratio",
    "triple_delimiter"
  ],
  "weights": [
    0.340105,
    -2.963898,
    -0.555302,
    -1.325476,
    0.805411,
    0.589872,
    0.850904,
    -0.674041,
    -0.121261,
    0.092027,
    -0.386876,
    -0.467757,
    3.147288,
    1.605218,
    -0.002303
  ],
  "threshold": 0.71
};
